log_dir: "logs/test"
save_freq: 20
device: "cuda"
epochs: 1000
batch_size: 64
pretrained_model: "logs/pretrained_models/pretrained.pth"

dataset_parasm:
  sr: 24000
  n_fft: 2048
  win_length: 1200
  hop_length: 300
  n_mels: 80

model_params:
  n_vocab: 35
  hidden_channels: 192
  filter_channels: 768
  filter_channels_dp: 256
  kernel_size: 3
  p_dropout: 0.1
  n_blocks_dec: 12
  n_layers_enc: 6
  n_heads: 2
  p_dropout_dec: 0.05
  dilation_rate: 1
  kernel_size_dec: 5
  n_block_layers: 4
  n_sqz: 2
  prenet: true
  mean_only: true
  hidden_channels_enc: 192
  hidden_channels_dec: 192
  windw_size: 4
  out_channels: 80
  n_speakers: 0
  gin_channels: 256

optimizer_params:
  lr: 0.001